export const IPC = {
  APP_OPEN_PROJECT: "app:open-project",
  STATE_LOAD: "state:load",
  STATE_SAVE: "state:save",
  GIT_CURRENT_BRANCH: "git:current-branch",
  GIT_BRANCH_STATS: "git:branch-stats",
  GIT_STATUS: "git:status",
  GIT_FILE_DIFF: "git:file-diff",
  GIT_STAGE: "git:stage",
  GIT_UNSTAGE: "git:unstage",
  GIT_DISCARD: "git:discard",
  GIT_COMMIT: "git:commit",
  FS_TREE_WITH_STATUS: "fs:tree-with-status",
  FS_READ_FILE: "fs:read-file",
  FS_WRITE_FILE: "fs:write-file",
  FS_WATCH: "fs:watch",
  FS_UNWATCH: "fs:unwatch",
  FS_CHANGED: "fs:changed",
  PTY_CREATE: "pty:create",
  PTY_WRITE: "pty:write",
  PTY_RESIZE: "pty:resize",
  PTY_DESTROY: "pty:destroy",
  PTY_REATTACH: "pty:reattach",
  PTY_DATA: "pty:data",
  PTY_EXIT: "pty:exit",
  CONTEXT_CREATE_BUNDLE: "context:create-bundle",
} as const;

