export const IPC = {
  APP_OPEN_PROJECT: "app:open-project",
  APP_OPEN_PROJECT_FROM_PATH: "app:open-project-from-path",
  APP_PICK_DIRECTORY: "app:pick-directory",
  STATE_LOAD: "state:load",
  STATE_SAVE: "state:save",
  GIT_CURRENT_BRANCH: "git:current-branch",
  GIT_BRANCH_STATS: "git:branch-stats",
  GIT_STATUS: "git:status",
  GIT_FILE_DIFF: "git:file-diff",
  GIT_STAGE: "git:stage",
  GIT_UNSTAGE: "git:unstage",
  GIT_DISCARD: "git:discard",
  GIT_COMMIT: "git:commit",
  GIT_PUSH: "git:push",
  GIT_PULL: "git:pull",
  GIT_GENERATE_COMMIT_MSG: "git:generate-commit-msg",
  GIT_WORKTREE_ADD: "git:worktree-add",
  GIT_WORKTREE_REMOVE: "git:worktree-remove",
  GIT_SCAN_WORKTREES: "git:scan-worktrees",
  GIT_FETCH: "git:fetch",
  GIT_REMOTE_BRANCHES: "git:remote-branches",
  GIT_PR_NUMBER: "git:pr-number",
  FS_TREE_WITH_STATUS: "fs:tree-with-status",
  FS_LIST_FILES: "fs:list-files",
  FS_READ_FILE: "fs:read-file",
  FS_READ_FILE_DATA_URL: "fs:read-file-data-url",
  FS_WRITE_FILE: "fs:write-file",
  FS_WATCH: "fs:watch",
  FS_UNWATCH: "fs:unwatch",
  FS_CHANGED: "fs:changed",
  PTY_CREATE: "pty:create",
  PTY_WRITE: "pty:write",
  PTY_RESIZE: "pty:resize",
  PTY_DESTROY: "pty:destroy",
  PTY_REATTACH: "pty:reattach",
  PTY_DATA: "pty:data",
  PTY_EXIT: "pty:exit",
  CONTEXT_CREATE_BUNDLE: "context:create-bundle",
  SHELL_OPEN_PATH: "shell:open-path",
  SHELL_OPEN_IN_IDE: "shell:open-in-ide",
  SHELL_OPEN_IN_TERMINAL: "shell:open-in-terminal",
  SHELL_SHOW_ITEM_IN_FOLDER: "shell:show-item-in-folder",
  SHELL_DETECT_IDES: "shell:detect-ides",
  SHELL_OPEN_WITH_IDE: "shell:open-with-ide",
  SHELL_DETECT_TERMINALS: "shell:detect-terminals",
  SHELL_OPEN_WITH_TERMINAL: "shell:open-with-terminal",
  SHELL_OPEN_EXTERNAL: "shell:open-external",
  AGENT_STATUS_UPDATE: "agent:status-update",
  AGENT_FOCUS_TAB: "agent:focus-tab",
  AGENT_RENAME_TAB: "agent:rename-tab",
  MENU_OPEN_SETTINGS: "menu:open-settings",
  // Browser (<webview>)
  BROWSER_CAPTURE_SCREENSHOT: "browser:capture-screenshot",
  BROWSER_SET_TOUCH_EMULATION: "browser:set-touch-emulation",
  BROWSER_ENABLE_CONSOLE: "browser:enable-console",
  BROWSER_DISABLE_CONSOLE: "browser:disable-console",
  BROWSER_CONSOLE_EVENT: "browser:console-event",
  BROWSER_OPEN_DEVTOOLS: "browser:open-devtools",
  BROWSER_POPOUT: "browser:popout",
  NOTIFICATION_PICK_AUDIO: "notification:pick-audio",
  NOTIFICATION_DELETE_AUDIO: "notification:delete-audio",
  APP_IS_FOCUSED: "app:is-focused",
  APP_FOCUS_WINDOW: "app:focus-window",
  FS_READ_ABS_FILE: "fs:read-abs-file",
  FS_READ_ABS_FILE_DATA_URL: "fs:read-abs-file-data-url",
  // LSP (text-based symbol search)
  LSP_GET_DEFINITION: "lsp:get-definition",
  // System emoji picker
  APP_SHOW_EMOJI_PANEL: "app:show-emoji-panel",
  // Pet overlay window
  PET_SETTINGS_CHANGED: "pet:settings-changed",
  PET_MOVE_WINDOW: "pet:move-window",
  PET_AGENT_STATUS_UPDATE: "pet:agent-status-update",
  PET_FOCUS_AGENT: "pet:focus-agent",
  // Pet approval UI
  PET_PERMISSION_REQUEST: "pet:permission-request",
  PET_PERMISSION_DECISION: "pet:permission-decision",
  PET_RESIZE_WINDOW: "pet:resize-window",
  AGENT_PERMISSION_REQUEST: "agent:permission-request",
  AGENT_PERMISSION_DECISION: "agent:permission-decision",
  AGENT_USER_PROMPT: "agent:user-prompt",
  AGENT_COMPLETION: "agent:completion",
  // Custom pet management
  PET_IMPORT: "pet:import",
  PET_DELETE: "pet:delete",
  PET_LIST: "pet:list",
  // Browser extensions
  EXTENSION_LIST: "extension:list",
  EXTENSION_INSTALL: "extension:install",
  EXTENSION_UNINSTALL: "extension:uninstall",
  EXTENSION_OPEN_POPUP: "extension:open-popup",
  EXTENSION_SCRIPTING_EXECUTE: "extension:scripting-execute",
  EXTENSION_SCRIPTING_INSERT_CSS: "extension:scripting-insert-css",
  /** Main → renderer: ask the browser window to create a tab and return its webContentsId */
  EXTENSION_TAB_CREATE: "extension:tab-create",
  /** Renderer → main: response with the new tab's webContentsId after dom-ready */
  EXTENSION_TAB_CREATED: "extension:tab-created",
} as const;
